name: 'Publish minepkg package'
description: 'Publishes a package on minepkg.io'
author: 'minepkg'
inputs:
  api-key:
    description: 'API key to authenticate. Pass a secret! See: https://preview.minepkg.io/docs/ci'
    required: true
  no-build:
    description: 'Skips the build step that the cli does by default'
    default: false
  working-directory:
    description: 'Working directory to use. Default is root of the project'
  release:
    description: 
      'Release version number to publish. You usually do not set this and use "minepkg bump" instead before publishing.'

  cli-version:
    description: 'The CLI version to install'
    default: 'latest'
  dry:
    description: 'Set to true to do a dry run without actually publishing'
runs:
  using: 'node12'
  main: 'dist/index.js'
